### ISSUE TITLE
App doenst work on your pc 

### ISSUE THREAD

**Issue by iTzFipi** [maael/giveaway-o-tron#4]
![image](https://github.com/maael/giveaway-o-tron/assets/142959176/6761c925-e9a4-4b53-9ac4-f157f69e667a)
so this is what appears when I try to open the bot..
tried everything but nothing worked... 
Running W11

thank you for the hard work <3

**Comment by maael** [comment]
This is solved by using the web app at https://giveaway-o-tron.mael.tech/app.

The desktop app is no longer supported.
